# Generated by Django 3.0 on 2019-12-13 19:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=2048)),
                ('unit_weight', models.CharField(max_length=512)),
                ('count', models.BigIntegerField(default=0)),
                ('upc', models.CharField(max_length=32)),
                ('msrp', models.CharField(max_length=512)),
            ],
        ),
    ]
